spring:
 datasource:
   url: jdbc:mysql://metzopole.xyz
   username: BeerAPI
   password: monkey
   driver-class-name: com.mysql.jdbc.Driver
 jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect