spring:
  application:
    name: beerapi
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#  boot:
#    admin:
#      client:
#        url: http://vps575474.ovh.net:8099

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always